### ISSUE TITLE
[BUG] API Documentation Redirects

### ISSUE THREAD

**Issue by Lioness100** [favna/nintendo-switch-eshop#1]
**Please describe the problem you are having in as much detail as possible:**

All links in the `Exports` category of the documentation point to the wrong URL. Instead of `/docs/Documentation/<type>/<name>`, it's jus't `/docs/<type>/<name>`

**To reproduce**

⇢ Navigate to https://favna.github.io/nintendo-switch-eshop/docs/Documentation
⇢ Click on a link to any Enumeration, Class, or Interface
⇢ Receive a 404

**Comment by favna** [comment]
grumble grumble. Stupid GitHub pages not reading links correctly.

I fixed it by moving the documentation to Vercel. New URL is https://nintendo-switch-eshop-favna.vercel.app
