### ISSUE TITLE
bug: getPrices throwing error

### ISSUE THREAD

**Issue by lucakaleron** [favna/nintendo-switch-eshop#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When trying to fetch the price via the getPrices function I get this error:

TypeError: gameIds.slice is not a function
    at getPrices (file:///D:/Programme/GitHub/playingg-server/node_modules/nintendo-switch-eshop/dist/index.mjs:422:31)
    at file:///D:/Programme/GitHub/playingg-server/utils/launcher/nintendo/nintendoFetch.js:3:21
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

### Steps To Reproduce

This is the code I ran:

import { getPrices } from 'nintendo-switch-eshop';

const price = await getPrices(2, 70010000000721);

console.log(price);

### Expected behavior

I should get a price of 4.99

**Comment by favna** [comment]
Please check the documentation (https://nintendo-switch-eshop-favna.vercel.app/docs/Documentation/#getprices) before creating a ticket. The type of `getPrices` is 
```ts
/**
 * Gets pricing information for the requested games. Paginates every 50 games.
 *
 * @param country A two digit country code. (ISO 3166-1 alpha-2 country code)
 * @param gameIds One or more NSUID of the corresponding games.
 * @param offset _(Optional)_ The offset to start at
 * @param prices _(Optional)_ An array of {@link TitleData}
 * @returns A promise containing the pricing information.
 */
export declare const getPrices: (country: string, gameIds: string[] | string, offset?: number, prices?: TitleData[]) => Promise<PriceResponse>;
```

**string** or **string array**, not number.

Furthermore, `2` is also invalid for `country`, it has to be a valid [ISO 3166-1 alpha-2 country code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)

**Comment by lucakaleron** [comment]
I tried using the region codes 1,2,3 after using the ISO codes failed:

import { getPrices } from 'nintendo-switch-eshop';

const getNintendoPrices = async () => {
    const prices = await getPrices(US, 70010000000721)

    console.log(prices);
}

getNintendoPrices();

Error:
file:///D:/Programme/GitHub/playingg-server/utils/launcher/nintendo/fetchNintendoApps.js:15
    const prices = await getPrices(US, 70010000000721)
                                   ^

ReferenceError: US is not defined
    at getNintendoPrices (file:///D:/Programme/GitHub/playingg-server/utils/launcher/nintendo/fetchNintendoApps.js:15:36)
    at file:///D:/Programme/GitHub/playingg-server/utils/launcher/nintendo/fetchNintendoApps.js:20:1
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
    
  I also tried UK and DE. Am I still using it wrong?

**Comment by favna** [comment]
`US` is not a string. `'US'` is. Please learn some coding basics first...

**Comment by lucakaleron** [comment]
omg ur totally right, im just dumb, sorry for the inconvenience
